version: "3"

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      # Start with the PF-Base Server Profile
      - SERVER_PROFILE_BASE_URL=https://github.com/cprice-ping/Profile-PF-Base.git
      - SERVER_PROFILE_BASE_PATH=pingfed
      # Add the PF-CIAM Profile to install the PingIDSDK Integration Kit
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-PF-CIAM.git
      - SERVER_PROFILE_PATH=pingfed
      - SERVER_PROFILE_PARENT=BASE
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ~/.pingidentity/devops
      - ./env_vars
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in lieu of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingfederate:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pf-config-base:
    image: postman/newman
    command: run https://www.getpostman.com/collections/2e0df14dcf26f1ddb39a -e postman_vars.json --insecure --ignore-redirects
    volumes: 
      # An environment file should be injected into the image - this file should contain your specfic info and secrets
      - ./pf_base_vars.json:/etc/newman/postman_vars.json
    networks:
      - pingnet

  # Provides the PF-CIAM API configuration
  pf-config-ciam:
    image: postman/newman
    command: run https://www.getpostman.com/collections/b17a3494b4f4d54de628 -e postman_vars.json --insecure --ignore-redirects
    volumes:
      # An environment file should be injected into the image - this file should contain your specfic info and secrets
      - ./pf_ciam_vars.json:/etc/newman/postman_vars.json
    networks:
      - pingnet

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-DelAdmin.git
      - SERVER_PROFILE_PATH=pingdir
 
      - SERVER_PROFILE_PARENT=BASELINE
      - SERVER_PROFILE_BASELINE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_BASELINE_PATH=baseline/pingdirectory
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingdirectory:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in

    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
                    
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8443:8443
    networks:
      - pingnet

  pingdelegator:
    image: pricecs/pingdelegator:4.0
    env_file:
      - ./env_vars
    ports:
      - 80:80
    networks:
      - pingnet

  smtp:
    image: bytemark/smtp
    restart: always
    networks:
      - pingnet

networks:
    pingnet: